version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "18:fd:7d:1d:58:cb:0a:2b:af:9e:28:4d:a5:5f:ba:92"
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn build

workflows:
  my-workflow:
    jobs:
      - build